version: "3"
services:
   app:
      build: .
      depends_on:
         - db
      command: npm run start
      ports:
        - 8080:8080
      environment:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USER=postgres
        - DB_PASS=123456
        - DB_NAME=liven
        - NODE_ENV=production
   db:
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=liven
      image: postgres