version: "3"
services:
  app:
    command: npm run test
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_NAME=liven_testing
      - NODE_ENV=testing
    volumes:
      - .:/usr/src/app
  db:
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=liven_testing
    volumes:
      - ~/.volumes/liven/teste_testing:/var/lib/postgresql/data
