version: "3"
services:
  app:
    command: npm run start
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_NAME=liven_development
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
  db:
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=liven_development
    volumes:
      - ~/.volumes/liven/teste:/var/lib/postgresql/data
